import type { Backlog } from "../model/schema.js";
import { blockersOf, requirementsOf, storyStatement, traceLine } from "./common.js";
import { toMermaid } from "./mermaid.js";

/** Review document: what a PM reads before pushing the backlog to a tracker. */
export function toMarkdown(backlog: Backlog): string {
  const points = backlog.stories.reduce((sum, s) => sum + (s.estimate?.points ?? 0), 0);
  const out: string[] = [
    `# Backlog: ${backlog.source.title}`,
    "",
    `Generated by \`${backlog.generator.name}\`${backlog.generator.model ? ` (${backlog.generator.model})` : ""} from ${backlog.source.path ? `\`${backlog.source.path}\`` : "the PRD"}.`,
    "",
    `| Epics | Stories | Story points | Requirements | Dependencies | Risks |`,
    `| ---: | ---: | ---: | ---: | ---: | ---: |`,
    `| ${backlog.epics.length} | ${backlog.stories.length} | ${points} | ${backlog.requirements.length} | ${backlog.dependencies.length} | ${backlog.risks.length} |`,
    "",
  ];

  for (const epic of backlog.epics) {
    out.push(`## ${epic.id}: ${epic.title}`, "");
    if (epic.description) out.push(epic.description, "");
    for (const story of backlog.stories.filter((s) => s.epicId === epic.id)) {
      const pts = story.estimate ? `${story.estimate.points} pts` : "unestimated";
      out.push(`### ${story.id}: ${story.title}`, "");
      out.push(storyStatement(story), "");
      out.push(`- Priority: ${story.priority} | Estimate: ${pts}`);
      if (story.estimate) out.push(`- Estimate rationale: ${story.estimate.rationale}`);
      const reqs = requirementsOf(story, backlog);
      for (const r of reqs) out.push(`- Traces to ${traceLine(r, backlog.source.path)}`);
      const blockers = blockersOf(story, backlog);
      if (blockers.length) out.push(`- Blocked by: ${blockers.map((b) => b.id).join(", ")}`);
      if (story.labels.length) out.push(`- Labels: ${story.labels.join(", ")}`);
      out.push("", "Acceptance criteria:", "");
      for (const c of story.acceptanceCriteria) {
        const tag = c.origin === "inferred" ? " _(inferred)_" : "";
        out.push(`- [ ] **Given** ${c.given}, **when** ${c.when}, **then** ${c.then}.${tag}`);
      }
      out.push("");
    }
  }

  out.push("## Dependencies", "", "```mermaid", toMermaid(backlog).trimEnd(), "```", "");
  out.push("Solid arrows are stated in the PRD; dotted arrows were inferred.", "");

  if (backlog.risks.length) {
    out.push("## Risks", "", "| ID | Risk | Likelihood | Impact | Mitigation | Related |");
    out.push("| --- | --- | --- | --- | --- | --- |");
    for (const r of backlog.risks) {
      const cell = (s: string) => s.replace(/\|/g, "\\|");
      out.push(
        `| ${r.id} | ${cell(r.description)} | ${r.likelihood} | ${r.impact} | ${cell(r.mitigation || "Not stated in PRD")} | ${r.relatedIds.join(", ")} |`,
      );
    }
    out.push("");
  }

  if (backlog.outOfScope.length) {
    out.push("## Out of scope (from the PRD)", "");
    for (const s of backlog.outOfScope) out.push(`- ${s.text} (line ${s.source.line})`);
    out.push("");
  }
  return out.join("\n");
}
